title: Paaras Purohit - APCSA Blog 2024
description: "August 2023 to June 2024"
owner_name: Nighthawk Coders
baseurl: "/apcsa-blog-2024"
github_username: PaarasPurohit
remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true